name: Opsgenie Prometheus Exporter Image

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    paths:
      - '*'
      - '.github/workflows/build.yml'
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: opsgenie-exporter
  IMAGE_VERSION: 0.0.1-r${{github.run_number}}
  IMAGE_REGISTRY: techniumlabs
  BASE_IMAGE_REPOSITORY: alpine
  IMAGE_REPOSITORY: opsgenie-exporter

jobs:

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build --file Dockerfile
            --label "org.opencontainers.image.source=https://github.com/techniumlabs/opsgenie-exporter"
            --label "org.opencontainers.image.revision=${{github.sha}}"
            --label "org.opencontainers.image.vendor=techniumlabs"
            --build-arg IMAGE_REGISTRY=${IMAGE_REGISTRY}
            --build-arg IMAGE_REPOSITORY=${BASE_IMAGE_REPOSITORY}
            --build-arg MAINTAINER=${MAINTAINER} --build-arg TIMEZONE=${TIMEZONE} --tag image .

        env:
          MAINTAINER: devops@techniumlabs.com
          TIMEZONE: Australia/Sydney

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image to docker hub
        run: |
          IMAGE_ID=techniumlabs/$IMAGE_NAME

          echo IMAGE_ID=$IMAGE_ID
          echo IMAGE_VERSION=$IMAGE_VERSION

          docker tag image $IMAGE_ID:$IMAGE_VERSION
          docker push $IMAGE_ID:$IMAGE_VERSION
